@base=https://dashboard.alpakasoelde.at
@devbase=http://localhost:7071

###

GET {{base}}/api/messages

###

@alpakaId=REPLACE-WITH-ALPAKA-ID

GET {{devbase}}/api/alpakas/{{alpakaId}}

###

@messageId=REPLACE-WITH-MESSAGE-ID

DELETE {{devbase}}/api/messages/{{messageId}}

###

POST {{devbase}}/api/events
Content-Type: application/json

{
  "eventType": "Impfen",
  "alpakaIds": ["REPLACE-WITH-ALPAKA-ID"],
  "eventDate": "2024-06-01",
  "cost": 45.5,
  "comment": "Impftermin beim Tierarzt"
}

###

GET {{devbase}}/api/events

###

GET {{devbase}}/api/gutscheine

###

POST {{devbase}}/api/gutscheine
Content-Type: application/json

{
  "gutscheinnummer": "202501",
  "kaufdatum": "2025-01-05",
  "betrag": 120,
  "eingeloestAm": null
}
