@base=https://alpakasoelde.at
@devbase=http://localhost:7071


###

POST {{base}}/api/send-message
Content-Type: application/x-www-form-urlencoded

name=TestName&email=test@example.com&message=Hello from .http file&phone=%2B43%20660%201234567&privacyConsent=true

###

POST {{devbase}}/api/send-message
Content-Type: application/x-www-form-urlencoded

name=Genuin&email=genuin@example.com&message=Hallo, wir wollen eine Führung auf Ihrem Hof buchen für eine Gruppe von 15 Personen im September. Wie sind Ihre Öffnungszeiten und Preise?&phone=%2B43%20660%201234567&privacyConsent=true

###

POST {{devbase}}/api/send-message
Content-Type: application/x-www-form-urlencoded

name=SpamBot&email=spammer@spam.example&message=CONGRATULATIONS YOU WON A FREE IPHONE click here https://bit.ly/free-iphone-123 to claim now limited offer!!!&privacyConsent=true

###

POST {{devbase}}/api/pageview
Content-Type: application/json

{
  "path": "/alpaka-wanderungen",
  "referrerHost": "www.google.at",
  "viewportWidth": 1440
}

###

POST {{devbase}}/api/pageview
Content-Type: application/json

{
  "path": "invalid-path",
  "referrerHost": "",
  "viewportWidth": -5
}
